sudo: required
services: 
    - docker

before_install:
    - docker build -t michalmatuszek/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true michalmatuszek/docker-react npm run test